### ISSUE TITLE
Create `Coordinates` class

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#10]
`Coordinates` stores the following data:
- `longitude: Double` - Longitude
- `latitude : Double` - Latitude
- `altitude : Double` - Altitude
Will automatically correct for transposed Lat/Lng value to reflect North America
DoD:  Class created to above specifications

**Comment by csuttner** [comment]
![Screen Shot 2020-05-06 at 8 41 00 AM](https://user-images.githubusercontent.com/26831719/81197589-53513d00-8f75-11ea-8a7b-246bc7d5540e.png)

@gomezfox Why wouldn't we use or subclass this class from the framework?

**Comment by csuttner** [comment]
https://developer.apple.com/documentation/corelocation/cllocation

**Comment by csuttner** [comment]
https://github.com/MobileApps-Cascadia/photopoints-ios/pull/22
