### ISSUE TITLE
Create ReST API endpoints for Items

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#101]
The existing static API is replaced with a responsive API that draws data from a CSV-formatted spreadsheet containing `Item` data and uses a JSON file as a template for each `Item`. Data is read-only by end users and accessible using the `GET` method. Encoding is UTF-8. Response codes of 200, 404, 405, or 500 are returned as appropriate.

DOD: CSV data is parsed and rearranged into JSON representation of items. Array containing all `Item` objects accessible using endpoint `photopoints/api/items` and individual items using endpoint `photopoints/api/item/{id}`

**Comment by gomezfox** [comment]
The API is running, and is currently available at [https://photopoints.gomezfox.net/apx/items](https://photopoints.gomezfox.net/apx/items)
Individual items are available at [https://photopoints.gomezfox.net/apx/items/28097](https://photopoints.gomezfox.net/apx/items/{id)

**Comment by csuttner** [comment]
@gomezfox if the API is running shouldn't this issue be closed?

**Comment by gomezfox** [comment]
Issue is complete
