### ISSUE TITLE
Create `Point` class which store location and type information for all `PointItem` types

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#11]
The `Point` class will store the basic information needed by all subclasses of `PointItem`:
- `id : Int` - Uniquiely identifies the item across all classes, datasources,
- `location : Coordinates`  -  Contains the geocoordinates of the Point
- `type : PointItemType`  -  Identifies the type/subclass of the PointItem
- `enabled : Bool`  -  Master control for whether the item is enabled/disabled

DoD:  Point class created to above specifications

**Comment by csuttner** [comment]
Please review and advise on any particulars. https://github.com/MobileApps-Cascadia/photopoints-ios/pull/23
