### ISSUE TITLE
Create `PointDetails` protocol (to be treated as abstract)

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#12]
For each subclass of `PointItem`, there is a corresponding subclass of `PointDetails` which contains all the set of data that is unique to that type (in contrast, `Point` contains the set of data required by all types).  Each will contain:
- `id: Int` - The id associated with these details
- `nameString: String` - Reasonably short string used to describe the item
- `description: String` - The long description of the item
The subclasses will also contain any additional fields related to the item
DoD:  `PointDetails` created as specified above

**Comment by csuttner** [comment]
https://github.com/MobileApps-Cascadia/photopoints-ios/pull/24

**Comment by csuttner** [comment]
Per the discussion of @gomezfox and I, qrCode is being moved to a different class/ issue.
Also, the id field will be added to this class.
