### ISSUE TITLE
Create `PointImage` class

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#13]
The `PointImage` class contains the following fields, which allow for the file location, classification, and association of images associated with a PointItem. Contains:
- `id : Int` - the ID of the associated `PointItem`
- `filename : String` - The filename of the image file (will be the hash of the file plus .png)
- `imagetype: String` - Stores semicolon separated tags to assign properties to the image
- `imageHeading : String` - Name type string that Identifies subject of photo
- `imageSource : String` - Identity of photographer or source 
- `imageLicense : String` - Image License / Permissions details

DoD: `PointImage` class created from above specs

**Comment by csuttner** [comment]
https://github.com/MobileApps-Cascadia/photopoints-ios/pull/25
