### ISSUE TITLE
Static mock database implemention

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#16]
Mimics the expected interface of the database, but is populated with and returns data as though it is really the database. In this way, switching of the actual database should be straightforward.
Entities to be included at this time include:
[Point]
[PlantDetails]
[CreekDetails]
[PointImage]
[Submissions]* optional at this time

DoD:  Mock database is created and contains accessors consistent with preliminary database access functions

**Comment by csuttner** [comment]
I think this was covered with #69. Can we close this @gomezfox?

**Comment by csuttner** [comment]
Covered with issue #69
