### ISSUE TITLE
Implement Observable Objects to automatically update UI elements

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#18]
Swift has built-in Observable Objects which will allow us to update UI elements, for instance those reflecting the survey status of an item and how many photos have been taken, on updates to relevant data.

DOD: Implement observable objects for all data display views.

**Comment by csuttner** [comment]
This issue is still relevant, but should be accomplished with swift's Observable Objects instead of writing custom protocols.

**Comment by csuttner** [comment]
this will be addressed in #194
