### ISSUE TITLE
Extend PointImage class to load and return images loaded from disk

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#19]
The `PointImage` class contains all the information to read and return images and their metadata, but the image itself is stored on the filesystem. A new class should allow images themselves to be read from the disk and returned for display.

DoD:  Class created with basic methods to store and retrieve images from document directory on disk

**Comment by csuttner** [comment]
@gomezfox when you say "appropriately resized" - does this mean that the disk read function will take in a size as an argument? I will first prototype this without any resizing.

**Comment by gomezfox** [comment]
There are portrait and landscape views that may be full screen, resized or trimmed in a variety of ways. There are complexities that we can address that later. For now, we'll just load the whole file as a bitmap, but for memory's usage, they will eventually need to be actually resized on load to fit the screen, width, tile, or thumbnail as as appropriate.

**Comment by csuttner** [comment]
Of course. Do you think the most elegant way to do this would be to create an enum for different size options and pass that in as an argument when retrieving an image from the disk?

**Comment by csuttner** [comment]
Moving this to the new project for sprint 2
