### ISSUE TITLE
Create PlantDetails and CreekDetails (subclasses of PointDetails)

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#20]
`PlantDetails` and `CreekDetails` will each extend `PointDetails` to provide the details specific to each of these item types.

DoD:  The above subclasses are created to reflect the database entities.  

Note:  These may actually be the entities themselves, if so, then PointDetails may need to become a protocol rather than a class

**Comment by csuttner** [comment]
@gomezfox is this issue still necessary given our change in architecture direction?

**Comment by gomezfox** [comment]
Due to a fundamental design change, this issue is now closed
