### ISSUE TITLE
Create lookup table for icon images

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#29]
Icons are part of the assets/resources of the project. A dictionary which assigns them to an item type for display on the map, along with a "tag" such as visited or unvisited would organize them and make it easy to get a reference to the right icon for the right status for display on map.  This would be a static object built upon app initialization that would provide requested icons via a function in the repository.

**Comment by csuttner** [comment]
No longer necessary
