### ISSUE TITLE
Create updated class UML document to include new architecture/model components

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#31]
The architecture and data model is ready for a diagram that would help indicate how the pieces all tie together.  
DoD:  The updated UML document is added to the documentation.

**Comment by csuttner** [comment]
@gomezfox focusing on just the model class diagram for now. Whether or not we store the item as an entity, I believe our diagram will be the same.

**Comment by csuttner** [comment]
@gomezfox @Teylan What do you think of this model diagram?
<img width="1091" alt="UML Class Diagram" src="https://user-images.githubusercontent.com/26831719/84451549-365cf900-ac08-11ea-85c1-f8a5596a6cc0.png">
