### ISSUE TITLE
Allow clustered photopoints to display as one point

### ISSUE THREAD

**Issue by Grant-Buchanan** [MobileApps-Cascadia/photopoints-ios#4]
Many of the photopoint locations are clustered together to the point where they don't display well on a map. We should implement a system that allows for point within a certain distance of each other to be displayed as a single point. This clustered point could then be tapped on to expand into its constituent points.

DOD:
Functionality as stated above in is place.

**Comment by csuttner** [comment]
Completed elsewhere.
