### ISSUE TITLE
Implement survey function

### ISSUE THREAD

**Issue by Grant-Buchanan** [MobileApps-Cascadia/photopoints-ios#5]
Once a user has scanned a photopoint they should have the ability to preform a survey related to the scanned point. From this screen the user should be able to take a picture as part of the survey.

DOD:
Survey screen is populated on questions based on point scanned
Survey screen allows the user to take a picture that will be displayed on the survey screen before submission.

**Comment by csuttner** [comment]
Being handled in smaller issues
