### ISSUE TITLE
Investigate Realm -> Dictionary -> Realm

### ISSUE THREAD

**Issue by csuttner** [MobileApps-Cascadia/photopoints-ios#50]
For our Detail field of Item, we currently have a dictionary of type `[String: String]`. This is a nice data structure to work with for key value pairs. In Realm, this will be represented in an entity with three fields:

`id: Int`
`key: String`
`value: String`

We're curious if we can convert queries from Realm directly into dictionaries which can be used to populate our Detail field in Item.

Otherwise, the next step will be to create a class which can perform this conversion for us.

DOD: the method for converting from realm query to dictionary has been discovered, or found not to exist.

**Comment by gomezfox** [comment]
Realm does not directly use `Dictionary`, but rather `List<T>` for persistent storage.  A `Detail` entity class was added and placed in a `List` to simulate the use of a `Dictionary`
