### ISSUE TITLE
Crete an entity for storage of user PhotoPoint contributions

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#54]
Creates a pair of classes for the storage of information about a user data submission.  The first, `SubmissionEntity` will store the following data for a planned or completed submission:
| Field | Description |
|--|--|
| ItemID  | ID of the `Item` associated with this submission                   |   
| GUID    | GUID assigned to all components of submission                      |   
| Count | The number of images associated with the submission     |
| Answers | Results of any textual survey questions associated with submission |   
| Status  | Flag to store the status of submission (Scheduled, Sent, etc)      |   

The second, `SubmissionImageEntity` will associate the URL of image files on the device with the GUID in the record created above. These images and their associated database entity may be deleted after submission.

DoD:  Both above entity classes are created as specified

**Comment by csuttner** [comment]
@gomezfox  please remove from this sprint

**Comment by gomezfox** [comment]
Continued as issue #104
