### ISSUE TITLE
Update initial JSON file to reflect current model

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#55]
The model has been updated to replace hard-coded database fields associated with a photopoint and determined by its type with a generic key/value model independent of type.  The JSON used to create the initial database needs to be updated to reflect this model
DoD:  JSON file updated to specs

**Comment by gomezfox** [comment]
Added a label field to Point, as map functionality in iOS currently uses textual identifiers

**Comment by csuttner** [comment]
@gomezfox I think this can be closed.
