### ISSUE TITLE
Research changing mapkit markers based on survey status

### ISSUE THREAD

**Issue by Grant-Buchanan** [MobileApps-Cascadia/photopoints-ios#6]
<s>In order to make it easier for people to survey all photopoints, we should keep track of which points the user has already surveyed on their map. When a point is tapped on you should be able to see if it has been surveyed or not.

DOD: The map markers for photopoints display a bit of text above them that either says "Surveyed" or "Not yet surveyed" when tapped on. </s>

This issue ended up encompassing too much and is being cut down to just the research portion. This issue now will serve to aggregate the results of the research into how to display custom mapkit markers.

As of now this is the source we're working with
https://developer.apple.com/documentation/mapkit/mapkit_annotations/annotating_a_map_with_custom_data

**Comment by csuttner** [comment]
This sounds fun :)

**Comment by Grant-Buchanan** [comment]
This issue ended up being way to broad and more complex than we thought it would be. Changed to better reflect progress.
