### ISSUE TITLE
Delete existing Realm database at launch

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#63]
The Realm database remains persistent as development occurs.  At this stage in development, it should be deleted on first run while the functionality to build and modify the database is implemented and tested
DoD: Realm is cleared on each run

**Comment by csuttner** [comment]
@gomezfox is this just clearing the data in Realm or deleting the actual database object?

**Comment by gomezfox** [comment]
Updated to delete the database if a migration needed.  Will be reversed when migrations are actually required.
NOTE:  Realm updated to 5.0.2 due to errors in opening Lists
