### ISSUE TITLE
Update map to use Item labels instead of Plant Common Names

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#83]
The current map uses a `Detail field from the `Item`.  The `Point`, the base data contained in an `Item` has a newly implemented `label` field which prevents the need to lazy-load the `Detail` and is intended to be used in cases exactly like that demanded by the map.
DoD:  The map will use the `label` field accessible through the `Item`

**Comment by csuttner** [comment]
This is complete.
