### ISSUE TITLE
Update Item to allow direct access of underlying data

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-ios#84]
Implements a way to access underlying data of `Item` without directly accessing its internal entities. The `Item` class is a composition of several Realm objects, including `Point` `[Detail]` and `[Image]`.  These entities are for internal use, and the key data should be accessible directly `Item`.  `Point` properties will be accessible directly from `Item`.  `[Detail]` properties, which are key/value will be available using a `subscript` extension to `Item` or as a `Dictionary` containing all properties. Image records will be available as an array of `Image` items.

DoD:  Internal database entities will be directly accessible from `Item` using subscript and new `ignored` (unsaved to Realm) properties in `Item`

**Comment by csuttner** [comment]
No longer using Realm. closed.
